"""Add diff_unified and diff_structured to Patch table

Revision ID: 495f65cb96e2
Revises: bcff3e1f3440
Create Date: 2025-12-03 20:50:25.823045

"""

from typing import Sequence


# revision identifiers, used by Alembic.
revision: str = "495f65cb96e2"
down_revision: str | Sequence[str] | None = "bcff3e1f3440"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
