"""Add mode field to Run table for test mode support

Revision ID: 9ffc3641511e
Revises: e22fa9fd58a6
Create Date: 2025-12-03 23:55:34.628966

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ffc3641511e"
down_revision: str | Sequence[str] | None = "e22fa9fd58a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs",
        sa.Column("mode", sa.Text(), nullable=False, server_default="PRODUCTION"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "mode")
    # ### end Alembic commands ###
