"""add_priority_to_rules

Revision ID: ab4e828d8044
Revises: 4a2518b2ffc4
Create Date: 2025-11-23 17:08:47.898328

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab4e828d8044"
down_revision: str | Sequence[str] | None = "4a2518b2ffc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rules", sa.Column("priority", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules", "priority")
    # ### end Alembic commands ###
