"""Add diff_unified and diff_structured to Patch table

Revision ID: bcff3e1f3440
Revises: 00f83fdbd8e1
Create Date: 2025-12-03 20:49:09.949516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcff3e1f3440'
down_revision: Union[str, Sequence[str], None] = '00f83fdbd8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patches', sa.Column('diff_unified', sa.Text(), nullable=True))
    op.add_column('patches', sa.Column('diff_structured', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patches', 'diff_structured')
    op.drop_column('patches', 'diff_unified')
    # ### end Alembic commands ###
