"""0001_init: Initial schema with Run, Change, Rule, Template, Patch

Revision ID: e166c3632866
Revises: 
Create Date: 2025-10-13 17:48:25.650125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e166c3632866'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.Text(), nullable=False),
    sa.Column('branch', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('Awaiting Review', 'Success', 'Failed', 'Manual Action Required', 'Completed (no patches)')", name='check_run_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_commit_sha'), 'runs', ['commit_sha'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.CheckConstraint("format IN ('Markdown', 'Storage')", name='check_template_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=True)
    op.create_table('changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('signature_before', sa.JSON(), nullable=True),
    sa.Column('signature_after', sa.JSON(), nullable=True),
    sa.CheckConstraint("change_type IN ('added', 'removed', 'modified')", name='check_change_type'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changes_run_id'), 'changes', ['run_id'], unique=False)
    op.create_table('patches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Text(), nullable=False),
    sa.Column('diff_before', sa.Text(), nullable=False),
    sa.Column('diff_after', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('Proposed', 'Approved', 'Rejected', 'Applied', 'RolledBack')", name='check_patch_status'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patches_run_id'), 'patches', ['run_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('selector', sa.Text(), nullable=False),
    sa.Column('space_key', sa.Text(), nullable=False),
    sa.Column('page_id', sa.Text(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_name'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_patches_run_id'), table_name='patches')
    op.drop_table('patches')
    op.drop_index(op.f('ix_changes_run_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_runs_commit_sha'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
